ACCESS_TOKEN = '<ACCESS_TOKEN>'
VERIFY_TOKEN = '<VERIFY_TOKEN>'
WIT_AI_ACCESS_TOKEN = 'IKJJJYYVR3X672DHFVS7U7C4L2MQSS2P'
GOODREADS_ACCESS_TOKEN = '<GOODREADS_ACCESS_TOKEN>'
WORDS_API_KEY = '<WORDS_API_KEY>'
<<<<<<< HEAD
JOKES_SOURCE_FILE = 'modules/src/jokes.json'
NYT_API_KEY = '<NYT_ARTICLES_API_KEY>'
=======
JOKES_SOURCE_FILE = 'data/jokes.json'
>>>>>>> 6db0d33671365d0bcf779c858788a3b9f50a178d
