# Facebook (+ Wit)
ACCESS_TOKEN = 'EAADjAJ2DMsYBAOqhYZCdoB2EDsZCCbED25ZCXSoF3zjwJrFxq3zO3iG2sa53nxibDI2yMvSZASCyrkiCZBiGKhTwgeZA3tSBBnsLRXUQlUS3HLZCuzzo4HZCnEUx8ThMPwXrbjvxV7laufWlQeztKerJOROecKyN9XMeNK7tUju1CgZDZD'
VERIFY_TOKEN = 'Revanth is my Creator'
WIT_AI_ACCESS_TOKEN = 'IKJJJYYVR3X672DHFVS7U7C4L2MQSS2P'

# Offline data sources
FACTS_SOURCE_FILE = 'data/facts.json'
JOKES_SOURCE_FILE = 'data/jokes.json'
QUOTES_SOURCE_FILE = 'data/quotes.json'

# API Keys
GOODREADS_ACCESS_TOKEN = '<<GOODREADS_ACCESS_TOKEN>>'
GOOGLE_URL_SHORTENER_API_KEY = '<<GOOGLE_URL_SHORTENER_API_KEY>>'
MAPQUEST_CONSUMER_KEY = '<<MAPQUEST_CONSUMER_KEY>>'
OPEN_WEATHER_MAP_ACCESS_TOKEN = '<<OPEN_WEATHER_MAP_ACCESS_TOKEN>>'
TIME_ZONE_DB_API_KEY = '<<TIME_ZONE_DB_API_KEY>>'
WORDS_API_KEY = '<<WORDS_API_KEY>>'
YOUTUBE_DATA_API_KEY = '<<YOUTUBE_DATA_API_KEY>>'
